### ISSUE TITLE
Please add a Git tag so that Package Control updates

### ISSUE THREAD

**Issue by trishume** [wmertens/sublime-nix#2]
After merging #1 you didn't push a Git tag so those of us who have installed sublime-nix via packagecontrol.io don't get the update. I really want to be able to type cmd+/ to comment/uncomment things.

I'm super glad this package exists though, thanks for making it!

@wmertens

**Comment by wmertens** [comment]
@trishume I am really sorry for missing this notification, I don't understand why my email filter missed it. I just did a release of v2.2, everything is working, right?

**Comment by trishume** [comment]
Yup I can now use `cmd+/`! Thank you!
