### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [wmertens/sublime-nix#3]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by domenkozar** [comment]
cc @wmertens - Github removed Nix because of this.

**Comment by wmertens** [comment]
@arfon @domenkozar Oops somehow missed this issue, weird. I'll move the package under MIT ASAP.

**Comment by wmertens** [comment]
@arfon it is now licensed under MIT license, what should I do to re-instate the highlighting?

**Comment by arfon** [comment]
@wmertens - I'll work on this tomorrow and highlighting should be restored by early next week (we have to cut a new gem).

Thanks for swapping out the license :zap:

**Comment by arfon** [comment]
PR for fix here: https://github.com/github/linguist/pull/2914

I'll cut a new gem early this week to get this live on GitHub.
